---
title: "Take report for coastal small boat surveys"
format: docx
editor: visual
---

```{r message=FALSE, warning=FALSE, echo=FALSE}
#| echo: false

rm(list = ls())
library(tidyverse)

source("CHLHP_PermitReport_fcns.R")

year <- 2025
# Extract the same information from the small boat database
data.year <- extract_take_data(year)
data.year$survey.data %>%
  group_by(PurposeName) %>%
  summarize(n = n()) -> survey.n

# Coastal Tursiops only
data.year$survey.data %>%
  filter(PurposeName == "Coastal Tursiops") -> coastal.Ttru.survey

data.year$sightings.data %>%
  right_join(coastal.Ttru.survey, by = "SurveyID") -> sightings.coastal.Ttru
  
sightings.coastal.Ttru %>%
  filter(CommonName == "California coastal bottlenose dolphin") -> sightings.Ttru

data.year$UAS.data %>%
  select(-c("SurveyDate", "SurveyNumber", "PurposeName", "year")) %>%
  right_join(coastal.Ttru.survey, by = "SurveyID") -> UAS.coastal.Ttru

UAS.coastal.Ttru %>%
  filter(CommonName == "California coastal bottlenose dolphin") %>%
  group_by(SightingID) %>%
  summarize(max.n = max(TargetCount, na.rm = T),
            sum.n = sum(TargetCount, na.rm = T))-> UAS.Ttru.summary


# Channel Islands gray whales
data.year$survey.data %>%
  filter(PurposeName == "Channel Islands Gray Whales") -> CI.Erob.survey

data.year$sightings.data %>%
  right_join(CI.Erob.survey, by = "SurveyID") -> sightings.CI.Erob
  
sightings.CI.Erob %>%
  filter(CommonName == "Gray whale") -> sightings.Erob

data.year$UAS.data %>%
  select(-c("SurveyDate", "SurveyNumber", "PurposeName", "year")) %>%
  right_join(CI.Erob.survey, by = "SurveyID") -> UAS.CI.Erob

UAS.CI.Erob %>%
  filter(CommonName == "Gray whale") %>%
  group_by(SightingID) %>%
  summarize(max.n = max(TargetCount, na.rm = T),
            sum.n = sum(TargetCount, na.rm = T))-> UAS.Erob.summary

data.year$survey.data %>%
  filter(PurposeName == "SD Cetacean") -> SD.Cetacean.survey

data.year$sightings.data %>%
  right_join(SD.Cetacean.survey, by = "SurveyID") -> sightings.SD.Cetacean

data.year$UAS.data %>%
  select(-c("SurveyDate", "SurveyNumber", "PurposeName", "year")) %>%
  right_join(SD.Cetacean.survey, by = "SurveyID") -> UAS.SD.Cetacean
  
data.year$survey.data %>%
  filter(PurposeName == "SCB eDNA sampling") -> SCB.eDNA.sampling

data.year$sightings.data %>%
  right_join(SCB.eDNA.sampling, by = "SurveyID") -> sightings.SCB.eDNA

data.year$UAS.data %>%
  select(-c("SurveyDate", "SurveyNumber", "PurposeName", "year")) %>%
  right_join(SCB.eDNA.sampling, by = "SurveyID") -> UAS.SCB.eDNA

```

## Take report

### Coastal small boat surveys


Cetacean surveys were conducted aboard the R/V Alexa K using handheld cameras and Uncrewed Aerial Systems (UAS), specifically the DJI Mavic 3 Pro. The scope of work encompassed: (1) dedicated coastal bottlenose dolphin surveys along the San Diego county coastline, (2) opportunistic coastal cetacean surveys, and (3) the gray whale photogrammetry survey in the Santa Barbara Channel. Additionally, the R/V Alexa K was deployed approximately monthly for eDNA water sampling, during which cetaceans of selected species were approached for photographic documentation.

Coastal Bottlenose Dolphin Surveys (Dedicated)
The dedicated coastal bottlenose dolphin survey was conducted `r survey.n %>% filter(PurposeName == "Coastal Tursiops") %>% pull(n)` times. These repeated surveys yielded `r sightings.Ttru %>% summarize(Best = sum(BestEstimate)) %>% pull(Best)` dolphin encounters (including `r sightings.Ttru %>% summarize(Best.calf = sum(BestCalvesEstimate, na.rm=T)) %>% pull(Best.calf)` calves). A total of `r sum(UAS.Ttru.summary$sum.n)` dolphins were documented in photographs and videos collected by UAS. As of January  `r year + 1`, image processing is incomplete, and the number of unique individuals photographed/videoed remains unknown. The data from these repeated surveys will be analyzed using capture-mark-recapture methods to estimate survival rates and abundance of coastal bottlenose dolphins. Furthermore, the data will be used to assess other social and biological parameters, such as occurrence, movements, and individual associations.

During eDNA sampling trips, photographs were also collected from bottlenose dolphins (n = 32, 1 calf). No UAS overflights were conducted on these animals.

Opportunistic Coastal Cetacean Surveys
During opportunistic surveys along the San Diego county coastline, various species were encountered, including `r unique(sightings.SD.Cetacean$CommonName)`. Photographic identification data were collected from fin whales (n = `r sightings.SD.Cetacean %>% filter(CommonName == "Fin whale") %>% pull(BestEstimate)`) and gray whales (n = `r sightings.SD.Cetacean %>% filter(CommonName == "Gray whale") %>% pull(BestEstimate)`). For these whales, UAS vertical video was also collected to assess body conditions. Common dolphins were not approached.

Gray Whale Photogrammetry Survey
The other dedicated small-boat based effort was the vertical image sampling of Eastern Pacific gray whales in the Santa Barbara Channel. This survey took place from `r min(CI.Erob.survey$SurveyDate)`  to `r max(CI.Erob.survey$SurveyDate)`. Over `r nrow(CI.Erob.survey)` days on the water, the DJI Mavic 3 Pro was flown over a total of `r sum(UAS.Erob.summary$sum.n)` whales. Photogrammetric measurements have been derived for a subset of these whales.

